#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpetCompanyDAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CarpetCompany")]
	public partial class MaliDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHesabMali(HesabMali instance);
    partial void UpdateHesabMali(HesabMali instance);
    partial void DeleteHesabMali(HesabMali instance);
    partial void InsertAsnadeDaryafti(AsnadeDaryafti instance);
    partial void UpdateAsnadeDaryafti(AsnadeDaryafti instance);
    partial void DeleteAsnadeDaryafti(AsnadeDaryafti instance);
    partial void InsertAsnadePardakhti(AsnadePardakhti instance);
    partial void UpdateAsnadePardakhti(AsnadePardakhti instance);
    partial void DeleteAsnadePardakhti(AsnadePardakhti instance);
    partial void InsertPardakhtAzHesab(PardakhtAzHesab instance);
    partial void UpdatePardakhtAzHesab(PardakhtAzHesab instance);
    partial void DeletePardakhtAzHesab(PardakhtAzHesab instance);
    partial void InsertVarizBeHesab(VarizBeHesab instance);
    partial void UpdateVarizBeHesab(VarizBeHesab instance);
    partial void DeleteVarizBeHesab(VarizBeHesab instance);
    partial void InsertHoghogh(Hoghogh instance);
    partial void UpdateHoghogh(Hoghogh instance);
    partial void DeleteHoghogh(Hoghogh instance);
    partial void InsertHazineEdari(HazineEdari instance);
    partial void UpdateHazineEdari(HazineEdari instance);
    partial void DeleteHazineEdari(HazineEdari instance);
    #endregion
		
		public MaliDataContext() : 
				base(global::CarpetCompanyDAL.Properties.Settings.Default.CarpetCompanyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MaliDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MaliDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MaliDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MaliDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HesabMali> HesabMalis
		{
			get
			{
				return this.GetTable<HesabMali>();
			}
		}
		
		public System.Data.Linq.Table<AsnadeDaryafti> AsnadeDaryaftis
		{
			get
			{
				return this.GetTable<AsnadeDaryafti>();
			}
		}
		
		public System.Data.Linq.Table<AsnadePardakhti> AsnadePardakhtis
		{
			get
			{
				return this.GetTable<AsnadePardakhti>();
			}
		}
		
		public System.Data.Linq.Table<PardakhtAzHesab> PardakhtAzHesabs
		{
			get
			{
				return this.GetTable<PardakhtAzHesab>();
			}
		}
		
		public System.Data.Linq.Table<VarizBeHesab> VarizBeHesabs
		{
			get
			{
				return this.GetTable<VarizBeHesab>();
			}
		}
		
		public System.Data.Linq.Table<Hoghogh> Hoghoghs
		{
			get
			{
				return this.GetTable<Hoghogh>();
			}
		}
		
		public System.Data.Linq.Table<HazineEdari> HazineEdaris
		{
			get
			{
				return this.GetTable<HazineEdari>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HesabMali")]
	public partial class HesabMali : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ShomareHesab;
		
		private string _SahebHesab;
		
		private string _NamHesab;
		
		private string _NamBank;
		
		private string _Tozihat;
		
		private decimal _Mojodi;
		
		private EntitySet<AsnadeDaryafti> _AsnadeDaryaftis;
		
		private EntitySet<AsnadePardakhti> _AsnadePardakhtis;
		
		private EntitySet<PardakhtAzHesab> _PardakhtAzHesabs;
		
		private EntitySet<VarizBeHesab> _VarizBeHesabs;
		
		private EntitySet<Hoghogh> _Hoghoghs;
		
		private EntitySet<HazineEdari> _HazineEdaris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnShomareHesabChanging(string value);
    partial void OnShomareHesabChanged();
    partial void OnSahebHesabChanging(string value);
    partial void OnSahebHesabChanged();
    partial void OnNamHesabChanging(string value);
    partial void OnNamHesabChanged();
    partial void OnNamBankChanging(string value);
    partial void OnNamBankChanged();
    partial void OnTozihatChanging(string value);
    partial void OnTozihatChanged();
    partial void OnMojodiChanging(decimal value);
    partial void OnMojodiChanged();
    #endregion
		
		public HesabMali()
		{
			this._AsnadeDaryaftis = new EntitySet<AsnadeDaryafti>(new Action<AsnadeDaryafti>(this.attach_AsnadeDaryaftis), new Action<AsnadeDaryafti>(this.detach_AsnadeDaryaftis));
			this._AsnadePardakhtis = new EntitySet<AsnadePardakhti>(new Action<AsnadePardakhti>(this.attach_AsnadePardakhtis), new Action<AsnadePardakhti>(this.detach_AsnadePardakhtis));
			this._PardakhtAzHesabs = new EntitySet<PardakhtAzHesab>(new Action<PardakhtAzHesab>(this.attach_PardakhtAzHesabs), new Action<PardakhtAzHesab>(this.detach_PardakhtAzHesabs));
			this._VarizBeHesabs = new EntitySet<VarizBeHesab>(new Action<VarizBeHesab>(this.attach_VarizBeHesabs), new Action<VarizBeHesab>(this.detach_VarizBeHesabs));
			this._Hoghoghs = new EntitySet<Hoghogh>(new Action<Hoghogh>(this.attach_Hoghoghs), new Action<Hoghogh>(this.detach_Hoghoghs));
			this._HazineEdaris = new EntitySet<HazineEdari>(new Action<HazineEdari>(this.attach_HazineEdaris), new Action<HazineEdari>(this.detach_HazineEdaris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShomareHesab", DbType="VarChar(19) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ShomareHesab
		{
			get
			{
				return this._ShomareHesab;
			}
			set
			{
				if ((this._ShomareHesab != value))
				{
					this.OnShomareHesabChanging(value);
					this.SendPropertyChanging();
					this._ShomareHesab = value;
					this.SendPropertyChanged("ShomareHesab");
					this.OnShomareHesabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SahebHesab", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string SahebHesab
		{
			get
			{
				return this._SahebHesab;
			}
			set
			{
				if ((this._SahebHesab != value))
				{
					this.OnSahebHesabChanging(value);
					this.SendPropertyChanging();
					this._SahebHesab = value;
					this.SendPropertyChanged("SahebHesab");
					this.OnSahebHesabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHesab", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NamHesab
		{
			get
			{
				return this._NamHesab;
			}
			set
			{
				if ((this._NamHesab != value))
				{
					this.OnNamHesabChanging(value);
					this.SendPropertyChanging();
					this._NamHesab = value;
					this.SendPropertyChanged("NamHesab");
					this.OnNamHesabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamBank", DbType="NVarChar(100)")]
		public string NamBank
		{
			get
			{
				return this._NamBank;
			}
			set
			{
				if ((this._NamBank != value))
				{
					this.OnNamBankChanging(value);
					this.SendPropertyChanging();
					this._NamBank = value;
					this.SendPropertyChanged("NamBank");
					this.OnNamBankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tozihat", DbType="NVarChar(MAX)")]
		public string Tozihat
		{
			get
			{
				return this._Tozihat;
			}
			set
			{
				if ((this._Tozihat != value))
				{
					this.OnTozihatChanging(value);
					this.SendPropertyChanging();
					this._Tozihat = value;
					this.SendPropertyChanged("Tozihat");
					this.OnTozihatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mojodi", DbType="Decimal(30,0) NOT NULL")]
		public decimal Mojodi
		{
			get
			{
				return this._Mojodi;
			}
			set
			{
				if ((this._Mojodi != value))
				{
					this.OnMojodiChanging(value);
					this.SendPropertyChanging();
					this._Mojodi = value;
					this.SendPropertyChanged("Mojodi");
					this.OnMojodiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabMali_AsnadeDaryafti", Storage="_AsnadeDaryaftis", ThisKey="ShomareHesab", OtherKey="ShomareHesab")]
		public EntitySet<AsnadeDaryafti> AsnadeDaryaftis
		{
			get
			{
				return this._AsnadeDaryaftis;
			}
			set
			{
				this._AsnadeDaryaftis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabMali_AsnadePardakhti", Storage="_AsnadePardakhtis", ThisKey="ShomareHesab", OtherKey="ShomareHesab")]
		public EntitySet<AsnadePardakhti> AsnadePardakhtis
		{
			get
			{
				return this._AsnadePardakhtis;
			}
			set
			{
				this._AsnadePardakhtis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabMali_PardakhtAzHesab", Storage="_PardakhtAzHesabs", ThisKey="ShomareHesab", OtherKey="ShomareHesab")]
		public EntitySet<PardakhtAzHesab> PardakhtAzHesabs
		{
			get
			{
				return this._PardakhtAzHesabs;
			}
			set
			{
				this._PardakhtAzHesabs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabMali_VarizBeHesab", Storage="_VarizBeHesabs", ThisKey="ShomareHesab", OtherKey="ShomareHesab")]
		public EntitySet<VarizBeHesab> VarizBeHesabs
		{
			get
			{
				return this._VarizBeHesabs;
			}
			set
			{
				this._VarizBeHesabs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabMali_Hoghogh", Storage="_Hoghoghs", ThisKey="ShomareHesab", OtherKey="ShomareHesab")]
		public EntitySet<Hoghogh> Hoghoghs
		{
			get
			{
				return this._Hoghoghs;
			}
			set
			{
				this._Hoghoghs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabMali_HazineEdari", Storage="_HazineEdaris", ThisKey="ShomareHesab", OtherKey="ShomareHesab")]
		public EntitySet<HazineEdari> HazineEdaris
		{
			get
			{
				return this._HazineEdaris;
			}
			set
			{
				this._HazineEdaris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AsnadeDaryaftis(AsnadeDaryafti entity)
		{
			this.SendPropertyChanging();
			entity.HesabMali = this;
		}
		
		private void detach_AsnadeDaryaftis(AsnadeDaryafti entity)
		{
			this.SendPropertyChanging();
			entity.HesabMali = null;
		}
		
		private void attach_AsnadePardakhtis(AsnadePardakhti entity)
		{
			this.SendPropertyChanging();
			entity.HesabMali = this;
		}
		
		private void detach_AsnadePardakhtis(AsnadePardakhti entity)
		{
			this.SendPropertyChanging();
			entity.HesabMali = null;
		}
		
		private void attach_PardakhtAzHesabs(PardakhtAzHesab entity)
		{
			this.SendPropertyChanging();
			entity.HesabMali = this;
		}
		
		private void detach_PardakhtAzHesabs(PardakhtAzHesab entity)
		{
			this.SendPropertyChanging();
			entity.HesabMali = null;
		}
		
		private void attach_VarizBeHesabs(VarizBeHesab entity)
		{
			this.SendPropertyChanging();
			entity.HesabMali = this;
		}
		
		private void detach_VarizBeHesabs(VarizBeHesab entity)
		{
			this.SendPropertyChanging();
			entity.HesabMali = null;
		}
		
		private void attach_Hoghoghs(Hoghogh entity)
		{
			this.SendPropertyChanging();
			entity.HesabMali = this;
		}
		
		private void detach_Hoghoghs(Hoghogh entity)
		{
			this.SendPropertyChanging();
			entity.HesabMali = null;
		}
		
		private void attach_HazineEdaris(HazineEdari entity)
		{
			this.SendPropertyChanging();
			entity.HesabMali = this;
		}
		
		private void detach_HazineEdaris(HazineEdari entity)
		{
			this.SendPropertyChanging();
			entity.HesabMali = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AsnadeDaryafti")]
	public partial class AsnadeDaryafti : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodeSenad;
		
		private string _ShomareHesab;
		
		private string _NamHesab;
		
		private string _DaryaftAz;
		
		private int _ShomareSenad;
		
		private string _TarikhSabt;
		
		private string _TarikhSarResid;
		
		private System.Nullable<decimal> _Price;
		
		private string _Tozihat;
		
		private string _Vaziat;
		
		private EntityRef<HesabMali> _HesabMali;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeSenadChanging(string value);
    partial void OnCodeSenadChanged();
    partial void OnShomareHesabChanging(string value);
    partial void OnShomareHesabChanged();
    partial void OnNamHesabChanging(string value);
    partial void OnNamHesabChanged();
    partial void OnDaryaftAzChanging(string value);
    partial void OnDaryaftAzChanged();
    partial void OnShomareSenadChanging(int value);
    partial void OnShomareSenadChanged();
    partial void OnTarikhSabtChanging(string value);
    partial void OnTarikhSabtChanged();
    partial void OnTarikhSarResidChanging(string value);
    partial void OnTarikhSarResidChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnTozihatChanging(string value);
    partial void OnTozihatChanged();
    partial void OnVaziatChanging(string value);
    partial void OnVaziatChanged();
    #endregion
		
		public AsnadeDaryafti()
		{
			this._HesabMali = default(EntityRef<HesabMali>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeSenad", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeSenad
		{
			get
			{
				return this._CodeSenad;
			}
			set
			{
				if ((this._CodeSenad != value))
				{
					this.OnCodeSenadChanging(value);
					this.SendPropertyChanging();
					this._CodeSenad = value;
					this.SendPropertyChanged("CodeSenad");
					this.OnCodeSenadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShomareHesab", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string ShomareHesab
		{
			get
			{
				return this._ShomareHesab;
			}
			set
			{
				if ((this._ShomareHesab != value))
				{
					if (this._HesabMali.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnShomareHesabChanging(value);
					this.SendPropertyChanging();
					this._ShomareHesab = value;
					this.SendPropertyChanged("ShomareHesab");
					this.OnShomareHesabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHesab", DbType="NVarChar(100)")]
		public string NamHesab
		{
			get
			{
				return this._NamHesab;
			}
			set
			{
				if ((this._NamHesab != value))
				{
					this.OnNamHesabChanging(value);
					this.SendPropertyChanging();
					this._NamHesab = value;
					this.SendPropertyChanged("NamHesab");
					this.OnNamHesabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaryaftAz", DbType="NVarChar(100)")]
		public string DaryaftAz
		{
			get
			{
				return this._DaryaftAz;
			}
			set
			{
				if ((this._DaryaftAz != value))
				{
					this.OnDaryaftAzChanging(value);
					this.SendPropertyChanging();
					this._DaryaftAz = value;
					this.SendPropertyChanged("DaryaftAz");
					this.OnDaryaftAzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShomareSenad", DbType="Int NOT NULL")]
		public int ShomareSenad
		{
			get
			{
				return this._ShomareSenad;
			}
			set
			{
				if ((this._ShomareSenad != value))
				{
					this.OnShomareSenadChanging(value);
					this.SendPropertyChanging();
					this._ShomareSenad = value;
					this.SendPropertyChanged("ShomareSenad");
					this.OnShomareSenadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikhSabt", DbType="NVarChar(10)")]
		public string TarikhSabt
		{
			get
			{
				return this._TarikhSabt;
			}
			set
			{
				if ((this._TarikhSabt != value))
				{
					this.OnTarikhSabtChanging(value);
					this.SendPropertyChanging();
					this._TarikhSabt = value;
					this.SendPropertyChanged("TarikhSabt");
					this.OnTarikhSabtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikhSarResid", DbType="NVarChar(10)")]
		public string TarikhSarResid
		{
			get
			{
				return this._TarikhSarResid;
			}
			set
			{
				if ((this._TarikhSarResid != value))
				{
					this.OnTarikhSarResidChanging(value);
					this.SendPropertyChanging();
					this._TarikhSarResid = value;
					this.SendPropertyChanged("TarikhSarResid");
					this.OnTarikhSarResidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(23,0)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tozihat", DbType="NVarChar(MAX)")]
		public string Tozihat
		{
			get
			{
				return this._Tozihat;
			}
			set
			{
				if ((this._Tozihat != value))
				{
					this.OnTozihatChanging(value);
					this.SendPropertyChanging();
					this._Tozihat = value;
					this.SendPropertyChanged("Tozihat");
					this.OnTozihatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vaziat", DbType="NVarChar(50)")]
		public string Vaziat
		{
			get
			{
				return this._Vaziat;
			}
			set
			{
				if ((this._Vaziat != value))
				{
					this.OnVaziatChanging(value);
					this.SendPropertyChanging();
					this._Vaziat = value;
					this.SendPropertyChanged("Vaziat");
					this.OnVaziatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabMali_AsnadeDaryafti", Storage="_HesabMali", ThisKey="ShomareHesab", OtherKey="ShomareHesab", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public HesabMali HesabMali
		{
			get
			{
				return this._HesabMali.Entity;
			}
			set
			{
				HesabMali previousValue = this._HesabMali.Entity;
				if (((previousValue != value) 
							|| (this._HesabMali.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HesabMali.Entity = null;
						previousValue.AsnadeDaryaftis.Remove(this);
					}
					this._HesabMali.Entity = value;
					if ((value != null))
					{
						value.AsnadeDaryaftis.Add(this);
						this._ShomareHesab = value.ShomareHesab;
					}
					else
					{
						this._ShomareHesab = default(string);
					}
					this.SendPropertyChanged("HesabMali");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AsnadePardakhti")]
	public partial class AsnadePardakhti : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodeSenad;
		
		private string _ShomareHesab;
		
		private string _NamHesab;
		
		private string _PardakhteBe;
		
		private string _ShomareSenad;
		
		private string _TarikhSabt;
		
		private string _TarikhSarResid;
		
		private System.Nullable<decimal> _Price;
		
		private string _Tozihat;
		
		private string _Vaziat;
		
		private EntityRef<HesabMali> _HesabMali;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeSenadChanging(string value);
    partial void OnCodeSenadChanged();
    partial void OnShomareHesabChanging(string value);
    partial void OnShomareHesabChanged();
    partial void OnNamHesabChanging(string value);
    partial void OnNamHesabChanged();
    partial void OnPardakhteBeChanging(string value);
    partial void OnPardakhteBeChanged();
    partial void OnShomareSenadChanging(string value);
    partial void OnShomareSenadChanged();
    partial void OnTarikhSabtChanging(string value);
    partial void OnTarikhSabtChanged();
    partial void OnTarikhSarResidChanging(string value);
    partial void OnTarikhSarResidChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnTozihatChanging(string value);
    partial void OnTozihatChanged();
    partial void OnVaziatChanging(string value);
    partial void OnVaziatChanged();
    #endregion
		
		public AsnadePardakhti()
		{
			this._HesabMali = default(EntityRef<HesabMali>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeSenad", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeSenad
		{
			get
			{
				return this._CodeSenad;
			}
			set
			{
				if ((this._CodeSenad != value))
				{
					this.OnCodeSenadChanging(value);
					this.SendPropertyChanging();
					this._CodeSenad = value;
					this.SendPropertyChanged("CodeSenad");
					this.OnCodeSenadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShomareHesab", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string ShomareHesab
		{
			get
			{
				return this._ShomareHesab;
			}
			set
			{
				if ((this._ShomareHesab != value))
				{
					if (this._HesabMali.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnShomareHesabChanging(value);
					this.SendPropertyChanging();
					this._ShomareHesab = value;
					this.SendPropertyChanged("ShomareHesab");
					this.OnShomareHesabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHesab", DbType="NVarChar(100)")]
		public string NamHesab
		{
			get
			{
				return this._NamHesab;
			}
			set
			{
				if ((this._NamHesab != value))
				{
					this.OnNamHesabChanging(value);
					this.SendPropertyChanging();
					this._NamHesab = value;
					this.SendPropertyChanged("NamHesab");
					this.OnNamHesabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PardakhteBe", DbType="NVarChar(100)")]
		public string PardakhteBe
		{
			get
			{
				return this._PardakhteBe;
			}
			set
			{
				if ((this._PardakhteBe != value))
				{
					this.OnPardakhteBeChanging(value);
					this.SendPropertyChanging();
					this._PardakhteBe = value;
					this.SendPropertyChanged("PardakhteBe");
					this.OnPardakhteBeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShomareSenad", DbType="NVarChar(50)")]
		public string ShomareSenad
		{
			get
			{
				return this._ShomareSenad;
			}
			set
			{
				if ((this._ShomareSenad != value))
				{
					this.OnShomareSenadChanging(value);
					this.SendPropertyChanging();
					this._ShomareSenad = value;
					this.SendPropertyChanged("ShomareSenad");
					this.OnShomareSenadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikhSabt", DbType="NVarChar(10)")]
		public string TarikhSabt
		{
			get
			{
				return this._TarikhSabt;
			}
			set
			{
				if ((this._TarikhSabt != value))
				{
					this.OnTarikhSabtChanging(value);
					this.SendPropertyChanging();
					this._TarikhSabt = value;
					this.SendPropertyChanged("TarikhSabt");
					this.OnTarikhSabtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikhSarResid", DbType="NVarChar(10)")]
		public string TarikhSarResid
		{
			get
			{
				return this._TarikhSarResid;
			}
			set
			{
				if ((this._TarikhSarResid != value))
				{
					this.OnTarikhSarResidChanging(value);
					this.SendPropertyChanging();
					this._TarikhSarResid = value;
					this.SendPropertyChanged("TarikhSarResid");
					this.OnTarikhSarResidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(23,0)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tozihat", DbType="NVarChar(MAX)")]
		public string Tozihat
		{
			get
			{
				return this._Tozihat;
			}
			set
			{
				if ((this._Tozihat != value))
				{
					this.OnTozihatChanging(value);
					this.SendPropertyChanging();
					this._Tozihat = value;
					this.SendPropertyChanged("Tozihat");
					this.OnTozihatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vaziat", DbType="NVarChar(50)")]
		public string Vaziat
		{
			get
			{
				return this._Vaziat;
			}
			set
			{
				if ((this._Vaziat != value))
				{
					this.OnVaziatChanging(value);
					this.SendPropertyChanging();
					this._Vaziat = value;
					this.SendPropertyChanged("Vaziat");
					this.OnVaziatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabMali_AsnadePardakhti", Storage="_HesabMali", ThisKey="ShomareHesab", OtherKey="ShomareHesab", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public HesabMali HesabMali
		{
			get
			{
				return this._HesabMali.Entity;
			}
			set
			{
				HesabMali previousValue = this._HesabMali.Entity;
				if (((previousValue != value) 
							|| (this._HesabMali.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HesabMali.Entity = null;
						previousValue.AsnadePardakhtis.Remove(this);
					}
					this._HesabMali.Entity = value;
					if ((value != null))
					{
						value.AsnadePardakhtis.Add(this);
						this._ShomareHesab = value.ShomareHesab;
					}
					else
					{
						this._ShomareHesab = default(string);
					}
					this.SendPropertyChanged("HesabMali");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PardakhtAzHesab")]
	public partial class PardakhtAzHesab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodePardakhti;
		
		private string _ShomareHesab;
		
		private string _NamHesab;
		
		private string _NamPardakhtKonande;
		
		private string _TarikhPardakht;
		
		private System.Nullable<decimal> _Price;
		
		private string _Tozihat;
		
		private EntityRef<HesabMali> _HesabMali;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodePardakhtiChanging(string value);
    partial void OnCodePardakhtiChanged();
    partial void OnShomareHesabChanging(string value);
    partial void OnShomareHesabChanged();
    partial void OnNamHesabChanging(string value);
    partial void OnNamHesabChanged();
    partial void OnNamPardakhtKonandeChanging(string value);
    partial void OnNamPardakhtKonandeChanged();
    partial void OnTarikhPardakhtChanging(string value);
    partial void OnTarikhPardakhtChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnTozihatChanging(string value);
    partial void OnTozihatChanged();
    #endregion
		
		public PardakhtAzHesab()
		{
			this._HesabMali = default(EntityRef<HesabMali>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodePardakhti", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodePardakhti
		{
			get
			{
				return this._CodePardakhti;
			}
			set
			{
				if ((this._CodePardakhti != value))
				{
					this.OnCodePardakhtiChanging(value);
					this.SendPropertyChanging();
					this._CodePardakhti = value;
					this.SendPropertyChanged("CodePardakhti");
					this.OnCodePardakhtiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShomareHesab", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string ShomareHesab
		{
			get
			{
				return this._ShomareHesab;
			}
			set
			{
				if ((this._ShomareHesab != value))
				{
					if (this._HesabMali.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnShomareHesabChanging(value);
					this.SendPropertyChanging();
					this._ShomareHesab = value;
					this.SendPropertyChanged("ShomareHesab");
					this.OnShomareHesabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHesab", DbType="NVarChar(100)")]
		public string NamHesab
		{
			get
			{
				return this._NamHesab;
			}
			set
			{
				if ((this._NamHesab != value))
				{
					this.OnNamHesabChanging(value);
					this.SendPropertyChanging();
					this._NamHesab = value;
					this.SendPropertyChanged("NamHesab");
					this.OnNamHesabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamPardakhtKonande", DbType="NVarChar(100)")]
		public string NamPardakhtKonande
		{
			get
			{
				return this._NamPardakhtKonande;
			}
			set
			{
				if ((this._NamPardakhtKonande != value))
				{
					this.OnNamPardakhtKonandeChanging(value);
					this.SendPropertyChanging();
					this._NamPardakhtKonande = value;
					this.SendPropertyChanged("NamPardakhtKonande");
					this.OnNamPardakhtKonandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikhPardakht", DbType="NVarChar(10)")]
		public string TarikhPardakht
		{
			get
			{
				return this._TarikhPardakht;
			}
			set
			{
				if ((this._TarikhPardakht != value))
				{
					this.OnTarikhPardakhtChanging(value);
					this.SendPropertyChanging();
					this._TarikhPardakht = value;
					this.SendPropertyChanged("TarikhPardakht");
					this.OnTarikhPardakhtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(23,0)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tozihat", DbType="NVarChar(MAX)")]
		public string Tozihat
		{
			get
			{
				return this._Tozihat;
			}
			set
			{
				if ((this._Tozihat != value))
				{
					this.OnTozihatChanging(value);
					this.SendPropertyChanging();
					this._Tozihat = value;
					this.SendPropertyChanged("Tozihat");
					this.OnTozihatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabMali_PardakhtAzHesab", Storage="_HesabMali", ThisKey="ShomareHesab", OtherKey="ShomareHesab", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public HesabMali HesabMali
		{
			get
			{
				return this._HesabMali.Entity;
			}
			set
			{
				HesabMali previousValue = this._HesabMali.Entity;
				if (((previousValue != value) 
							|| (this._HesabMali.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HesabMali.Entity = null;
						previousValue.PardakhtAzHesabs.Remove(this);
					}
					this._HesabMali.Entity = value;
					if ((value != null))
					{
						value.PardakhtAzHesabs.Add(this);
						this._ShomareHesab = value.ShomareHesab;
					}
					else
					{
						this._ShomareHesab = default(string);
					}
					this.SendPropertyChanged("HesabMali");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VarizBeHesab")]
	public partial class VarizBeHesab : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodeVariz;
		
		private string _ShomareHesab;
		
		private string _NamHesab;
		
		private string _NamVarizKonande;
		
		private string _TarikhVarizi;
		
		private System.Nullable<decimal> _Price;
		
		private string _Tozihat;
		
		private EntityRef<HesabMali> _HesabMali;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeVarizChanging(string value);
    partial void OnCodeVarizChanged();
    partial void OnShomareHesabChanging(string value);
    partial void OnShomareHesabChanged();
    partial void OnNamHesabChanging(string value);
    partial void OnNamHesabChanged();
    partial void OnNamVarizKonandeChanging(string value);
    partial void OnNamVarizKonandeChanged();
    partial void OnTarikhVariziChanging(string value);
    partial void OnTarikhVariziChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnTozihatChanging(string value);
    partial void OnTozihatChanged();
    #endregion
		
		public VarizBeHesab()
		{
			this._HesabMali = default(EntityRef<HesabMali>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeVariz", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeVariz
		{
			get
			{
				return this._CodeVariz;
			}
			set
			{
				if ((this._CodeVariz != value))
				{
					this.OnCodeVarizChanging(value);
					this.SendPropertyChanging();
					this._CodeVariz = value;
					this.SendPropertyChanged("CodeVariz");
					this.OnCodeVarizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShomareHesab", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string ShomareHesab
		{
			get
			{
				return this._ShomareHesab;
			}
			set
			{
				if ((this._ShomareHesab != value))
				{
					if (this._HesabMali.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnShomareHesabChanging(value);
					this.SendPropertyChanging();
					this._ShomareHesab = value;
					this.SendPropertyChanged("ShomareHesab");
					this.OnShomareHesabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHesab", DbType="NVarChar(100)")]
		public string NamHesab
		{
			get
			{
				return this._NamHesab;
			}
			set
			{
				if ((this._NamHesab != value))
				{
					this.OnNamHesabChanging(value);
					this.SendPropertyChanging();
					this._NamHesab = value;
					this.SendPropertyChanged("NamHesab");
					this.OnNamHesabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamVarizKonande", DbType="NVarChar(100)")]
		public string NamVarizKonande
		{
			get
			{
				return this._NamVarizKonande;
			}
			set
			{
				if ((this._NamVarizKonande != value))
				{
					this.OnNamVarizKonandeChanging(value);
					this.SendPropertyChanging();
					this._NamVarizKonande = value;
					this.SendPropertyChanged("NamVarizKonande");
					this.OnNamVarizKonandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikhVarizi", DbType="NVarChar(10)")]
		public string TarikhVarizi
		{
			get
			{
				return this._TarikhVarizi;
			}
			set
			{
				if ((this._TarikhVarizi != value))
				{
					this.OnTarikhVariziChanging(value);
					this.SendPropertyChanging();
					this._TarikhVarizi = value;
					this.SendPropertyChanged("TarikhVarizi");
					this.OnTarikhVariziChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(23,0)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tozihat", DbType="NVarChar(MAX)")]
		public string Tozihat
		{
			get
			{
				return this._Tozihat;
			}
			set
			{
				if ((this._Tozihat != value))
				{
					this.OnTozihatChanging(value);
					this.SendPropertyChanging();
					this._Tozihat = value;
					this.SendPropertyChanged("Tozihat");
					this.OnTozihatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabMali_VarizBeHesab", Storage="_HesabMali", ThisKey="ShomareHesab", OtherKey="ShomareHesab", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public HesabMali HesabMali
		{
			get
			{
				return this._HesabMali.Entity;
			}
			set
			{
				HesabMali previousValue = this._HesabMali.Entity;
				if (((previousValue != value) 
							|| (this._HesabMali.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HesabMali.Entity = null;
						previousValue.VarizBeHesabs.Remove(this);
					}
					this._HesabMali.Entity = value;
					if ((value != null))
					{
						value.VarizBeHesabs.Add(this);
						this._ShomareHesab = value.ShomareHesab;
					}
					else
					{
						this._ShomareHesab = default(string);
					}
					this.SendPropertyChanged("HesabMali");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hoghogh")]
	public partial class Hoghogh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodeHoghogh;
		
		private string _ShomareHesab;
		
		private string _Nam;
		
		private string _Tarikh;
		
		private string _NoaHoghogh;
		
		private decimal _price;
		
		private string _Tozihat;
		
		private EntityRef<HesabMali> _HesabMali;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeHoghoghChanging(string value);
    partial void OnCodeHoghoghChanged();
    partial void OnShomareHesabChanging(string value);
    partial void OnShomareHesabChanged();
    partial void OnNamChanging(string value);
    partial void OnNamChanged();
    partial void OnTarikhChanging(string value);
    partial void OnTarikhChanged();
    partial void OnNoaHoghoghChanging(string value);
    partial void OnNoaHoghoghChanged();
    partial void OnpriceChanging(decimal value);
    partial void OnpriceChanged();
    partial void OnTozihatChanging(string value);
    partial void OnTozihatChanged();
    #endregion
		
		public Hoghogh()
		{
			this._HesabMali = default(EntityRef<HesabMali>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeHoghogh", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeHoghogh
		{
			get
			{
				return this._CodeHoghogh;
			}
			set
			{
				if ((this._CodeHoghogh != value))
				{
					this.OnCodeHoghoghChanging(value);
					this.SendPropertyChanging();
					this._CodeHoghogh = value;
					this.SendPropertyChanged("CodeHoghogh");
					this.OnCodeHoghoghChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShomareHesab", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string ShomareHesab
		{
			get
			{
				return this._ShomareHesab;
			}
			set
			{
				if ((this._ShomareHesab != value))
				{
					if (this._HesabMali.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnShomareHesabChanging(value);
					this.SendPropertyChanging();
					this._ShomareHesab = value;
					this.SendPropertyChanged("ShomareHesab");
					this.OnShomareHesabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="NVarChar(100)")]
		public string Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this.OnNamChanging(value);
					this.SendPropertyChanging();
					this._Nam = value;
					this.SendPropertyChanged("Nam");
					this.OnNamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarikh", DbType="NVarChar(10)")]
		public string Tarikh
		{
			get
			{
				return this._Tarikh;
			}
			set
			{
				if ((this._Tarikh != value))
				{
					this.OnTarikhChanging(value);
					this.SendPropertyChanging();
					this._Tarikh = value;
					this.SendPropertyChanged("Tarikh");
					this.OnTarikhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoaHoghogh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NoaHoghogh
		{
			get
			{
				return this._NoaHoghogh;
			}
			set
			{
				if ((this._NoaHoghogh != value))
				{
					this.OnNoaHoghoghChanging(value);
					this.SendPropertyChanging();
					this._NoaHoghogh = value;
					this.SendPropertyChanged("NoaHoghogh");
					this.OnNoaHoghoghChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(20,0) NOT NULL")]
		public decimal price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tozihat", DbType="NVarChar(MAX)")]
		public string Tozihat
		{
			get
			{
				return this._Tozihat;
			}
			set
			{
				if ((this._Tozihat != value))
				{
					this.OnTozihatChanging(value);
					this.SendPropertyChanging();
					this._Tozihat = value;
					this.SendPropertyChanged("Tozihat");
					this.OnTozihatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabMali_Hoghogh", Storage="_HesabMali", ThisKey="ShomareHesab", OtherKey="ShomareHesab", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public HesabMali HesabMali
		{
			get
			{
				return this._HesabMali.Entity;
			}
			set
			{
				HesabMali previousValue = this._HesabMali.Entity;
				if (((previousValue != value) 
							|| (this._HesabMali.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HesabMali.Entity = null;
						previousValue.Hoghoghs.Remove(this);
					}
					this._HesabMali.Entity = value;
					if ((value != null))
					{
						value.Hoghoghs.Add(this);
						this._ShomareHesab = value.ShomareHesab;
					}
					else
					{
						this._ShomareHesab = default(string);
					}
					this.SendPropertyChanged("HesabMali");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HazineEdari")]
	public partial class HazineEdari : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodeHazine;
		
		private string _ShomareHesab;
		
		private string _NamHazine;
		
		private string _TarikhPardakht;
		
		private System.Nullable<decimal> _price;
		
		private string _Tozihat;
		
		private EntityRef<HesabMali> _HesabMali;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeHazineChanging(string value);
    partial void OnCodeHazineChanged();
    partial void OnShomareHesabChanging(string value);
    partial void OnShomareHesabChanged();
    partial void OnNamHazineChanging(string value);
    partial void OnNamHazineChanged();
    partial void OnTarikhPardakhtChanging(string value);
    partial void OnTarikhPardakhtChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void OnTozihatChanging(string value);
    partial void OnTozihatChanged();
    #endregion
		
		public HazineEdari()
		{
			this._HesabMali = default(EntityRef<HesabMali>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeHazine", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeHazine
		{
			get
			{
				return this._CodeHazine;
			}
			set
			{
				if ((this._CodeHazine != value))
				{
					this.OnCodeHazineChanging(value);
					this.SendPropertyChanging();
					this._CodeHazine = value;
					this.SendPropertyChanged("CodeHazine");
					this.OnCodeHazineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShomareHesab", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string ShomareHesab
		{
			get
			{
				return this._ShomareHesab;
			}
			set
			{
				if ((this._ShomareHesab != value))
				{
					if (this._HesabMali.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnShomareHesabChanging(value);
					this.SendPropertyChanging();
					this._ShomareHesab = value;
					this.SendPropertyChanged("ShomareHesab");
					this.OnShomareHesabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHazine", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NamHazine
		{
			get
			{
				return this._NamHazine;
			}
			set
			{
				if ((this._NamHazine != value))
				{
					this.OnNamHazineChanging(value);
					this.SendPropertyChanging();
					this._NamHazine = value;
					this.SendPropertyChanged("NamHazine");
					this.OnNamHazineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikhPardakht", DbType="NVarChar(10)")]
		public string TarikhPardakht
		{
			get
			{
				return this._TarikhPardakht;
			}
			set
			{
				if ((this._TarikhPardakht != value))
				{
					this.OnTarikhPardakhtChanging(value);
					this.SendPropertyChanging();
					this._TarikhPardakht = value;
					this.SendPropertyChanged("TarikhPardakht");
					this.OnTarikhPardakhtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tozihat", DbType="NVarChar(MAX)")]
		public string Tozihat
		{
			get
			{
				return this._Tozihat;
			}
			set
			{
				if ((this._Tozihat != value))
				{
					this.OnTozihatChanging(value);
					this.SendPropertyChanging();
					this._Tozihat = value;
					this.SendPropertyChanged("Tozihat");
					this.OnTozihatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabMali_HazineEdari", Storage="_HesabMali", ThisKey="ShomareHesab", OtherKey="ShomareHesab", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public HesabMali HesabMali
		{
			get
			{
				return this._HesabMali.Entity;
			}
			set
			{
				HesabMali previousValue = this._HesabMali.Entity;
				if (((previousValue != value) 
							|| (this._HesabMali.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HesabMali.Entity = null;
						previousValue.HazineEdaris.Remove(this);
					}
					this._HesabMali.Entity = value;
					if ((value != null))
					{
						value.HazineEdaris.Add(this);
						this._ShomareHesab = value.ShomareHesab;
					}
					else
					{
						this._ShomareHesab = default(string);
					}
					this.SendPropertyChanged("HesabMali");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
