#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpetCompanyDAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CarpetCompany")]
	public partial class SenadHaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHesabKol(HesabKol instance);
    partial void UpdateHesabKol(HesabKol instance);
    partial void DeleteHesabKol(HesabKol instance);
    partial void InsertHesabMoin(HesabMoin instance);
    partial void UpdateHesabMoin(HesabMoin instance);
    partial void DeleteHesabMoin(HesabMoin instance);
    partial void InsertHesabTafsili(HesabTafsili instance);
    partial void UpdateHesabTafsili(HesabTafsili instance);
    partial void DeleteHesabTafsili(HesabTafsili instance);
    partial void InsertSenad(Senad instance);
    partial void UpdateSenad(Senad instance);
    partial void DeleteSenad(Senad instance);
    #endregion
		
		public SenadHaDataContext() : 
				base(global::CarpetCompanyDAL.Properties.Settings.Default.CarpetCompanyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SenadHaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SenadHaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SenadHaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SenadHaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HesabKol> HesabKols
		{
			get
			{
				return this.GetTable<HesabKol>();
			}
		}
		
		public System.Data.Linq.Table<HesabMoin> HesabMoins
		{
			get
			{
				return this.GetTable<HesabMoin>();
			}
		}
		
		public System.Data.Linq.Table<HesabTafsili> HesabTafsilis
		{
			get
			{
				return this.GetTable<HesabTafsili>();
			}
		}
		
		public System.Data.Linq.Table<Senad> Senads
		{
			get
			{
				return this.GetTable<Senad>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HesabKol")]
	public partial class HesabKol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodeKol;
		
		private string _OnvanKol;
		
		private EntitySet<HesabMoin> _HesabMoins;
		
		private EntitySet<Senad> _Senads;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeKolChanging(string value);
    partial void OnCodeKolChanged();
    partial void OnOnvanKolChanging(string value);
    partial void OnOnvanKolChanged();
    #endregion
		
		public HesabKol()
		{
			this._HesabMoins = new EntitySet<HesabMoin>(new Action<HesabMoin>(this.attach_HesabMoins), new Action<HesabMoin>(this.detach_HesabMoins));
			this._Senads = new EntitySet<Senad>(new Action<Senad>(this.attach_Senads), new Action<Senad>(this.detach_Senads));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeKol", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeKol
		{
			get
			{
				return this._CodeKol;
			}
			set
			{
				if ((this._CodeKol != value))
				{
					this.OnCodeKolChanging(value);
					this.SendPropertyChanging();
					this._CodeKol = value;
					this.SendPropertyChanged("CodeKol");
					this.OnCodeKolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnvanKol", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string OnvanKol
		{
			get
			{
				return this._OnvanKol;
			}
			set
			{
				if ((this._OnvanKol != value))
				{
					this.OnOnvanKolChanging(value);
					this.SendPropertyChanging();
					this._OnvanKol = value;
					this.SendPropertyChanged("OnvanKol");
					this.OnOnvanKolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabKol_HesabMoin", Storage="_HesabMoins", ThisKey="CodeKol", OtherKey="CodeKol")]
		public EntitySet<HesabMoin> HesabMoins
		{
			get
			{
				return this._HesabMoins;
			}
			set
			{
				this._HesabMoins.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabKol_Senad", Storage="_Senads", ThisKey="CodeKol", OtherKey="CodeKol")]
		public EntitySet<Senad> Senads
		{
			get
			{
				return this._Senads;
			}
			set
			{
				this._Senads.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HesabMoins(HesabMoin entity)
		{
			this.SendPropertyChanging();
			entity.HesabKol = this;
		}
		
		private void detach_HesabMoins(HesabMoin entity)
		{
			this.SendPropertyChanging();
			entity.HesabKol = null;
		}
		
		private void attach_Senads(Senad entity)
		{
			this.SendPropertyChanging();
			entity.HesabKol = this;
		}
		
		private void detach_Senads(Senad entity)
		{
			this.SendPropertyChanging();
			entity.HesabKol = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HesabMoin")]
	public partial class HesabMoin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodeMoin;
		
		private string _OnvanMoin;
		
		private string _CodeKol;
		
		private EntitySet<HesabTafsili> _HesabTafsilis;
		
		private EntityRef<HesabKol> _HesabKol;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeMoinChanging(string value);
    partial void OnCodeMoinChanged();
    partial void OnOnvanMoinChanging(string value);
    partial void OnOnvanMoinChanged();
    partial void OnCodeKolChanging(string value);
    partial void OnCodeKolChanged();
    #endregion
		
		public HesabMoin()
		{
			this._HesabTafsilis = new EntitySet<HesabTafsili>(new Action<HesabTafsili>(this.attach_HesabTafsilis), new Action<HesabTafsili>(this.detach_HesabTafsilis));
			this._HesabKol = default(EntityRef<HesabKol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeMoin", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeMoin
		{
			get
			{
				return this._CodeMoin;
			}
			set
			{
				if ((this._CodeMoin != value))
				{
					this.OnCodeMoinChanging(value);
					this.SendPropertyChanging();
					this._CodeMoin = value;
					this.SendPropertyChanged("CodeMoin");
					this.OnCodeMoinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnvanMoin", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string OnvanMoin
		{
			get
			{
				return this._OnvanMoin;
			}
			set
			{
				if ((this._OnvanMoin != value))
				{
					this.OnOnvanMoinChanging(value);
					this.SendPropertyChanging();
					this._OnvanMoin = value;
					this.SendPropertyChanged("OnvanMoin");
					this.OnOnvanMoinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeKol", DbType="VarChar(15)")]
		public string CodeKol
		{
			get
			{
				return this._CodeKol;
			}
			set
			{
				if ((this._CodeKol != value))
				{
					if (this._HesabKol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodeKolChanging(value);
					this.SendPropertyChanging();
					this._CodeKol = value;
					this.SendPropertyChanged("CodeKol");
					this.OnCodeKolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabMoin_HesabTafsili", Storage="_HesabTafsilis", ThisKey="CodeMoin", OtherKey="CodeMoin")]
		public EntitySet<HesabTafsili> HesabTafsilis
		{
			get
			{
				return this._HesabTafsilis;
			}
			set
			{
				this._HesabTafsilis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabKol_HesabMoin", Storage="_HesabKol", ThisKey="CodeKol", OtherKey="CodeKol", IsForeignKey=true, DeleteRule="CASCADE")]
		public HesabKol HesabKol
		{
			get
			{
				return this._HesabKol.Entity;
			}
			set
			{
				HesabKol previousValue = this._HesabKol.Entity;
				if (((previousValue != value) 
							|| (this._HesabKol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HesabKol.Entity = null;
						previousValue.HesabMoins.Remove(this);
					}
					this._HesabKol.Entity = value;
					if ((value != null))
					{
						value.HesabMoins.Add(this);
						this._CodeKol = value.CodeKol;
					}
					else
					{
						this._CodeKol = default(string);
					}
					this.SendPropertyChanged("HesabKol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HesabTafsilis(HesabTafsili entity)
		{
			this.SendPropertyChanging();
			entity.HesabMoin = this;
		}
		
		private void detach_HesabTafsilis(HesabTafsili entity)
		{
			this.SendPropertyChanging();
			entity.HesabMoin = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HesabTafsili")]
	public partial class HesabTafsili : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodeTafsili;
		
		private string _OnvanTafsili;
		
		private string _CodeMoin;
		
		private EntityRef<HesabMoin> _HesabMoin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeTafsiliChanging(string value);
    partial void OnCodeTafsiliChanged();
    partial void OnOnvanTafsiliChanging(string value);
    partial void OnOnvanTafsiliChanged();
    partial void OnCodeMoinChanging(string value);
    partial void OnCodeMoinChanged();
    #endregion
		
		public HesabTafsili()
		{
			this._HesabMoin = default(EntityRef<HesabMoin>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeTafsili", DbType="VarChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodeTafsili
		{
			get
			{
				return this._CodeTafsili;
			}
			set
			{
				if ((this._CodeTafsili != value))
				{
					this.OnCodeTafsiliChanging(value);
					this.SendPropertyChanging();
					this._CodeTafsili = value;
					this.SendPropertyChanged("CodeTafsili");
					this.OnCodeTafsiliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OnvanTafsili", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string OnvanTafsili
		{
			get
			{
				return this._OnvanTafsili;
			}
			set
			{
				if ((this._OnvanTafsili != value))
				{
					this.OnOnvanTafsiliChanging(value);
					this.SendPropertyChanging();
					this._OnvanTafsili = value;
					this.SendPropertyChanged("OnvanTafsili");
					this.OnOnvanTafsiliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeMoin", DbType="VarChar(20)")]
		public string CodeMoin
		{
			get
			{
				return this._CodeMoin;
			}
			set
			{
				if ((this._CodeMoin != value))
				{
					if (this._HesabMoin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodeMoinChanging(value);
					this.SendPropertyChanging();
					this._CodeMoin = value;
					this.SendPropertyChanged("CodeMoin");
					this.OnCodeMoinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabMoin_HesabTafsili", Storage="_HesabMoin", ThisKey="CodeMoin", OtherKey="CodeMoin", IsForeignKey=true, DeleteRule="CASCADE")]
		public HesabMoin HesabMoin
		{
			get
			{
				return this._HesabMoin.Entity;
			}
			set
			{
				HesabMoin previousValue = this._HesabMoin.Entity;
				if (((previousValue != value) 
							|| (this._HesabMoin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HesabMoin.Entity = null;
						previousValue.HesabTafsilis.Remove(this);
					}
					this._HesabMoin.Entity = value;
					if ((value != null))
					{
						value.HesabTafsilis.Add(this);
						this._CodeMoin = value.CodeMoin;
					}
					else
					{
						this._CodeMoin = default(string);
					}
					this.SendPropertyChanged("HesabMoin");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Senad")]
	public partial class Senad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ShomareSenad;
		
		private string _CodeKol;
		
		private string _CodeMoein;
		
		private string _CodeTafsili;
		
		private string _NamHesab;
		
		private string _SharheSenad;
		
		private string _TarikhSenad;
		
		private System.Nullable<decimal> _Bedehkar;
		
		private System.Nullable<decimal> _Bestankar;
		
		private EntityRef<HesabKol> _HesabKol;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnShomareSenadChanging(string value);
    partial void OnShomareSenadChanged();
    partial void OnCodeKolChanging(string value);
    partial void OnCodeKolChanged();
    partial void OnCodeMoeinChanging(string value);
    partial void OnCodeMoeinChanged();
    partial void OnCodeTafsiliChanging(string value);
    partial void OnCodeTafsiliChanged();
    partial void OnNamHesabChanging(string value);
    partial void OnNamHesabChanged();
    partial void OnSharheSenadChanging(string value);
    partial void OnSharheSenadChanged();
    partial void OnTarikhSenadChanging(string value);
    partial void OnTarikhSenadChanged();
    partial void OnBedehkarChanging(System.Nullable<decimal> value);
    partial void OnBedehkarChanged();
    partial void OnBestankarChanging(System.Nullable<decimal> value);
    partial void OnBestankarChanged();
    #endregion
		
		public Senad()
		{
			this._HesabKol = default(EntityRef<HesabKol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShomareSenad", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ShomareSenad
		{
			get
			{
				return this._ShomareSenad;
			}
			set
			{
				if ((this._ShomareSenad != value))
				{
					this.OnShomareSenadChanging(value);
					this.SendPropertyChanging();
					this._ShomareSenad = value;
					this.SendPropertyChanged("ShomareSenad");
					this.OnShomareSenadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeKol", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CodeKol
		{
			get
			{
				return this._CodeKol;
			}
			set
			{
				if ((this._CodeKol != value))
				{
					if (this._HesabKol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodeKolChanging(value);
					this.SendPropertyChanging();
					this._CodeKol = value;
					this.SendPropertyChanged("CodeKol");
					this.OnCodeKolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeMoein", DbType="VarChar(20)")]
		public string CodeMoein
		{
			get
			{
				return this._CodeMoein;
			}
			set
			{
				if ((this._CodeMoein != value))
				{
					this.OnCodeMoeinChanging(value);
					this.SendPropertyChanging();
					this._CodeMoein = value;
					this.SendPropertyChanged("CodeMoein");
					this.OnCodeMoeinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeTafsili", DbType="VarChar(25)")]
		public string CodeTafsili
		{
			get
			{
				return this._CodeTafsili;
			}
			set
			{
				if ((this._CodeTafsili != value))
				{
					this.OnCodeTafsiliChanging(value);
					this.SendPropertyChanging();
					this._CodeTafsili = value;
					this.SendPropertyChanged("CodeTafsili");
					this.OnCodeTafsiliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHesab", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string NamHesab
		{
			get
			{
				return this._NamHesab;
			}
			set
			{
				if ((this._NamHesab != value))
				{
					this.OnNamHesabChanging(value);
					this.SendPropertyChanging();
					this._NamHesab = value;
					this.SendPropertyChanged("NamHesab");
					this.OnNamHesabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SharheSenad", DbType="NVarChar(MAX)")]
		public string SharheSenad
		{
			get
			{
				return this._SharheSenad;
			}
			set
			{
				if ((this._SharheSenad != value))
				{
					this.OnSharheSenadChanging(value);
					this.SendPropertyChanging();
					this._SharheSenad = value;
					this.SendPropertyChanged("SharheSenad");
					this.OnSharheSenadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarikhSenad", DbType="NVarChar(10)")]
		public string TarikhSenad
		{
			get
			{
				return this._TarikhSenad;
			}
			set
			{
				if ((this._TarikhSenad != value))
				{
					this.OnTarikhSenadChanging(value);
					this.SendPropertyChanging();
					this._TarikhSenad = value;
					this.SendPropertyChanged("TarikhSenad");
					this.OnTarikhSenadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bedehkar", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Bedehkar
		{
			get
			{
				return this._Bedehkar;
			}
			set
			{
				if ((this._Bedehkar != value))
				{
					this.OnBedehkarChanging(value);
					this.SendPropertyChanging();
					this._Bedehkar = value;
					this.SendPropertyChanged("Bedehkar");
					this.OnBedehkarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bestankar", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Bestankar
		{
			get
			{
				return this._Bestankar;
			}
			set
			{
				if ((this._Bestankar != value))
				{
					this.OnBestankarChanging(value);
					this.SendPropertyChanging();
					this._Bestankar = value;
					this.SendPropertyChanged("Bestankar");
					this.OnBestankarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HesabKol_Senad", Storage="_HesabKol", ThisKey="CodeKol", OtherKey="CodeKol", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public HesabKol HesabKol
		{
			get
			{
				return this._HesabKol.Entity;
			}
			set
			{
				HesabKol previousValue = this._HesabKol.Entity;
				if (((previousValue != value) 
							|| (this._HesabKol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HesabKol.Entity = null;
						previousValue.Senads.Remove(this);
					}
					this._HesabKol.Entity = value;
					if ((value != null))
					{
						value.Senads.Add(this);
						this._CodeKol = value.CodeKol;
					}
					else
					{
						this._CodeKol = default(string);
					}
					this.SendPropertyChanged("HesabKol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
